### ISSUE TITLE
When install: ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by loicbcn** [enricofer/qgis_report_wizard#2]
Hello, I notice this issue at the end of the install:
>ImportError: cannot import name 'OrderedDict' from 'typing' (C:\PROGRA~1\QGIS3.16\apps\Python37\lib\typing.py) 

I m using **3.16.14-Hannover**

Changing
```Python
from typing import OrderedDict
```
by 

```Python
from collections import OrderedDict
```
open a new error: 
>"TypeError: 'QVariant' object is not subscriptable"

Version 1.0.1 isn' t very stable, at less for me.
Thanks.

**Comment by enricofer** [comment]
Thanks for submission.
the import line is no longer needed so it can be deleted

Can you submit the dataset that throws the other error?   Or at least the layer fields list,
There could be a data type not handled by the plugin.

**Comment by loicbcn** [comment]
Hello, there are no datasets ..., the errors happened trying install the extension: I try to show you the problem here:

![image](https://user-images.githubusercontent.com/8970033/149969117-2f9150fd-2c95-4bbc-99c9-264b588759c1.png)

**Comment by enricofer** [comment]
I mean this error:

    "TypeError: 'QVariant' object is not subscriptable"

**Comment by loicbcn** [comment]
Ok,
sorry, i m just a qgis user who wanted to try an extension "stable".
Please write the optimal QGIS version to use your plugin (in the QGIS repo).
Thanks.

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/qgis_report_wizard/commit/7e721b28a838b8f5940d531fbf4b0d52cf1d81ba
