### ISSUE TITLE
Feature request: Save hyptertext output to unzipped folder

### ISSUE THREAD

**Issue by velle** [enricofer/qgis_report_wizard#4]
I would prefer that the output was saved to a folder, and not into a zipped file like "main.html.zip". I am currently editing both template and project data, and continously I need to unpack the zip file to see the result. This process is unnecessarily tedious imo. If there are good reasons for zipping, then how about offering a checkbox that lets the user decide if it should be zipped or not. Sincerely.

**Comment by enricofer** [comment]
new feature: https://github.com/enricofer/qgis_report_wizard/commit/6e725718e970690a55d66c0ca9e1763300689f89
