### ISSUE TITLE
image filter fails when extent argument is a list

### ISSUE THREAD

**Issue by velle** [enricofer/qgis_report_wizard#5]
The documentation for the *image* filter says:

> extent:	A extent QgsRectangle object or a [xmin,ymin,xmax,ymax] list
> that specify the map context of the image

Therefore, I believe the following lines should work

-         `<img src="{{ globals|image(200,200,extent=[1000000, 7000000, 2000000, 8000000])}}">`
-         `<img src="{{ globals|image(200,200,extent=globals.bbox)}}">`

But they both fail with the following error: 

```
File "/home/jdoe/myproj/rapport/html/main.html", line 40, in <module>
<img src="{{ globals|image(200,200,extent=[1000000, 7000000, 2000000, 8000000])}}">
File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/report_engines.py", line 118, in image_render
return self.export_canvas_image(view_box, width, height, theme, img_temppath if not self.embed_images else None, around_border)
File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/report_engines.py", line 76, in export_canvas_image
dim = box.xMaximum() - box.xMinimum()
AttributeError: 'list' object has no attribute 'xMaximum'
```

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/qgis_report_wizard/commit/cb5d821027b06ff4b10ec2850b043c7826c4e83e
thanks for submission.
