### ISSUE TITLE
Jinja2 3.0.0 compatibility: cannot import name 'evalcontextfilter'

### ISSUE THREAD

**Issue by ygversil** [enricofer/qgis_report_wizard#7]
The plugin is not be compatible with Jinja2 3+. When this Jinja2 version is used, trying to install or activate the plugin within QGIS will raise the following error: `cannot import name 'evalcontextfilter' from 'jinja2'`.

It seems to be documented: https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.pass_eval_context

**Comment by enricofer** [comment]
secretary python module is a bit outdated and doesn't support jinja2 3+
you should downgrade it at least to 2.11.3:
`pip install jinja2==2.11.3`

https://github.com/enricofer/qgis_report_wizard/blob/6e725718e970690a55d66c0ca9e1763300689f89/.github/workflows/docker-image.yml#L48

**Comment by enricofer** [comment]
You need a further module downgrade:
`pip install MarkupSafe==1.1.0`

https://github.com/enricofer/qgis_report_wizard/blob/6e725718e970690a55d66c0ca9e1763300689f89/.github/workflows/docker-image.yml#L49
